### PR TITLE
Testimonial

### PR DESCRIPTION
**Pull request by maliknajeeb113**
Added: Testimonial Carousel with indicator dots

### CODE REVIEW

**Review by SawanKumarBhagat — CHANGES_REQUESTED** [review]
We haven't pushed Contact feature component to main yet, this should not be present in your PR.

Suggestion: Remove all Contact related files from this PR and Keep files only related to your feature.

**Review by SawanKumarBhagat — APPROVED** [review]

**Review by SawanKumarBhagat — CHANGES_REQUESTED** [review]
We haven't pushed Contact feature component to main yet, this should not be present in your PR.

Suggestion: Remove all Contact related files from this PR and Keep files only related to your feature.

**Comment by maliknajeeb113** [comment]
@SawanKumarBhagat Changes are made. Review and let me know if anything else is required.

**Review by SawanKumarBhagat — APPROVED** [review]

**Comment by SawanKumarBhagat** [comment]
@maliknajeeb113 Looks good to me. Merging this PR.

**Pull request merged**
